version: '3.1'

services:
  mongo:
    container_name: mongo-api
    image: mongo
    restart: always
    environment:
     - MONGODB_USERNAME=api_user
     - MONGODB_PASSWORD=test123_pass
     - MONGODB_DATABASE=api
  golang-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-golang-api}
    volumes:
      - "./golang-gin-mongo/:/home"
    ports:
      - "80:8000"
    restart: always
